name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build maven package
        run: mvn package -DskipTests
      - name: Test
        run: mvn test

